### ISSUE TITLE
目录超长溢出屏幕问题

### ISSUE THREAD

**Issue by jalr4ever** [getgridea/gridea-theme-notes#8]
你好，EryouHao！很喜欢您开发的这款简洁的主题！满足基本的博客需求，但最近发现，目录的显示在右侧是写死的，会有超长溢出屏幕的问题... 是否可以修复一下目录的问题呢？
示例如下，博客的目录很长，会出现溢出屏幕的问题：
![image](https://user-images.githubusercontent.com/23929139/71703338-07e42200-2e0f-11ea-9f2e-235448447f95.png)
![image](https://user-images.githubusercontent.com/23929139/71703351-129eb700-2e0f-11ea-8270-89eddfa4d4f5.png)

**Comment by kevinspider** [comment]
同样遇到这个问题

**Comment by jalr4ever** [comment]
> 同样遇到这个问题

我转移到隔壁的 next 主题了，有目录折叠特性，看来这个作者也没有更新这个主题的想法

**Comment by kevinspider** [comment]
> > 同样遇到这个问题
> 
> 我转移到隔壁的 next 主题了，有目录折叠特性，看来这个作者也没有更新这个主题的想法

我自己手动修改了
~/Documents/Gridea/themes/notes/assets/styles/components/post.less

在对应的 .markdownIt-TOC 中设置 height 和 overflow 属性
height: calc(90vh);
overflow: scroll;
